# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: circleci/node:11.14
version: 2
jobs:
    build:
        <<: *defaults
        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-

            - run: npm install

            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}

            - run: npm run build

            - store_test_results:
                path: build/test-results

            - store_artifacts:
                path: build/native-injects
                prefix: build


            - persist_to_workspace:
                root: "."
                paths:
                    - build/native-injects
    deploy:
        <<: *defaults
        steps:
            - attach_workspace:
                at: "."

            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            - run: cd build/native-injects && npm publish


workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build:
                filters:
                    tags:
                        only: /.*/
            - deploy:
                requires:
                    - build
                filters:
                    tags:
                        only: /v.*/
                    branches:
                        ignore: /.*/
